name: Docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno environment
        uses: denolib/setup-deno@v2.3.0
        with:
          deno-version: v1.x

      - name: Run lume
        run: |
          cd docs
          deno eval --unstable "import site from './_config.js'; site.options.location = new URL('https://oscarotero.github.io/lume/'); site.build();"

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.0.1
        with:
          build_dir: docs/_site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
