name: Test Windows

on: [push, pull_request]

jobs:
  build:
    name: Run tests
    runs-on:
      - ubuntu-latest
      - windows-latest
      - macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Deno environment
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Test installation
        run: |
          deno run -A install.ts

      - name: Run tests
        run: |
          deno test --unstable -A
